// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9Zt0OpwEvVRQ7SNDXCD0U8s7NLkSMrs',
    appId: '1:1060875580781:web:4ebe6138e2b85cda309664',
    messagingSenderId: '1060875580781',
    projectId: 'kbo-ratkum-e658c',
    authDomain: 'kbo-ratkum-e658c.firebaseapp.com',
    storageBucket: 'kbo-ratkum-e658c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4wumuX90dUpDDIWpTSIJY-s3u2tIwgAY',
    appId: '1:1060875580781:android:662eaf44901d4a70309664',
    messagingSenderId: '1060875580781',
    projectId: 'kbo-ratkum-e658c',
    storageBucket: 'kbo-ratkum-e658c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgn92OYG7HdPETx2rLsSsnidPzTZgh5K0',
    appId: '1:1060875580781:ios:3905744e89a36475309664',
    messagingSenderId: '1060875580781',
    projectId: 'kbo-ratkum-e658c',
    storageBucket: 'kbo-ratkum-e658c.appspot.com',
    iosClientId: '1060875580781-ua5ink4j5buqlquqcjusfpnejuan3nj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolAul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgn92OYG7HdPETx2rLsSsnidPzTZgh5K0',
    appId: '1:1060875580781:ios:3905744e89a36475309664',
    messagingSenderId: '1060875580781',
    projectId: 'kbo-ratkum-e658c',
    storageBucket: 'kbo-ratkum-e658c.appspot.com',
    iosClientId: '1060875580781-ua5ink4j5buqlquqcjusfpnejuan3nj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolAul',
  );
}
